### ISSUE TITLE
Losing all map markers

### ISSUE THREAD

**Issue by thrandisher** [eideehi/valheim-automatics#40] opened 2022-12-30 18:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.0

### Is this a bug caused by this mod alone?

This mod alone did not reproduce the bug

### List of mods to reproduce bug

Jewelcrafting 1.3.13 by Smothbrain

### What happened?

Ive added about 6 differnt kinds of jewel mineable nodes from Jewelcraft under the mineral section, clicked on auto marking and in the mining section ive selected auto mining.  For mining section i have ticked, need pickaxe equiped.

The nodes show up on minimap and main map. After mining them the node marker disapears as with the new option for that, but all map markers that i have placed or from boss stones or anything on entire map disapear.

Identifer:RawOrangeGemstone
label:Humite Gems
Pattern: $jc_raw_Orange_Gemstone

that is what i used for one minable type..

Cat woke up and is wanting his morning luvin so sorry for typos and rushness. He's already closed my window out twice. :/

### Steps to reproduce the bug

1. Find gem, make sure it is auto marked on map.
2. Make a marker close by so you can see it on minimap
3. Switch to pickaxe and auto mine gem site,
4. Watch all your markers disapear

**Comment by thrandisher** [comment] 2022-12-30 19:35
I forgot to add that if i uncheck auto pin on the nodes, the automatic mining still works and all my user made markers DONT disapear.

**Comment by DAOWAce** [comment] 2023-01-04 11:24
I have everything in the mod disabled except auto map pinning.  I don't believe I've changed the defaults of settings besides unchecking numerous clutter pins (flora, mobs).

I just lost half my map pins during my last session when exploring a bit.  Didn't see any errors in the log.  Not using other mods that add game content (just QoL stuff for a vanilla playthrough).

So, same issue of markers disappearing, but different cause.

**Comment by APost-It** [comment] 2023-01-09 20:47
I am also losing all my map pins. It has deleted everything, even my spawn point and boss locations. It deletes pins that I have placed and it deletes pins that the "Save Static" option automatically places. There are no errors in the logs during play sessions when I notice that my map pins have disappeared. I can regain some of my map pins back by interacting with the cartography table, but eventually this mod deletes those pins again. There doesn't seem to be any certain action that causes the map pins to disappear.

It doesn't seem to matter whether or not I'm in the area, it has deleted all my map pins near any of my houses and it has deleted map pins that I haven't been to since mapping them.

I do not have the Jewelcrafting mod.

This is the only mod I have that interacts with the map.

I hope this issue gets resolved because I love this mod and this particular feature.

**Comment by DAOWAce** [comment] 2023-01-10 19:51
To update (and send a notification out), I've found 1.3.2 working with Mistlands just fine, and does not have the marker deletion bug.

Just remember to restore your backup config for the older version, or if you didn't back it up, remove it.  I don't think it'll handle a version downgrade gracefully, but I've not tested it either.

**Comment by eideehi** [comment] 2023-03-09 15:15
I'm sorry for destroying your important data. I have just identified the cause of the bug, and will release a bug fix over the weekend. Thank you for your information.

**Comment by turnerlewis** [comment] 2023-03-09 15:43
Same issue - but came here to see the developer has responded 25 minutes ago. I will suffer for now until the fix is posted. Keep up the amazing work eideehi! <3

**Comment by eideehi** [comment] 2023-03-10 15:41
This bug has been fixed in commit f96f7be81e7924fad80eca19ea537dff2bc560f0.

Please wait for the bug fix release. Thank you for reporting the bug.

**Closed** 2023-03-11 12:01 UTC
Labels: bug, unintended behavior

**Comment by APost-It** [comment] 2023-03-11 22:38
Thank you for looking into this bug. Definitely my favorite mod!
