### ISSUE TITLE
Update auto pickup to stop overencumbering users. Or add a variable to stop autopickup after player has reached x weight

### ISSUE THREAD

**Issue by calebsw83** [eideehi/valheim-automatics#44] opened 2023-01-10 21:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.0

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### What happened?

If you're at your weight limit and trying to walk anywhere, you start picking up rocks and other trash overencumbering you. Since there's no plan to be able to filter items, which would be the most effective solution, at least add a means to stop auto pickup when a condition is met. Either set it at 300/450 or allow the user to set it, similar to how there's a minimum item number cutoff for automatic processing.  Thanks. 

### Steps to reproduce the bug

Just walk around at full weight capacity

**Comment by eideehi** [comment] 2023-03-09 14:15
Indeed, picking up items unnecessarily can be a problem. I will add an option in a future update.

**Comment by eideehi** [comment] 2023-03-09 14:19
Although this issue has not been resolved, it is not a bug, so we will close it for now.

**Closed by eideehi** 2023-03-09 14:19 UTC
