### ISSUE TITLE
Option request: Auto Store only in containers that already have 1+ of the item

### ISSUE THREAD

**Issue by Darrken** [eideehi/valheim-automatics#50] opened 2023-03-23 16:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.3

### Is this a bug caused by this mod alone?

The bug was reproduced with this mod alone

### What happened?

Not a bug, obviously, but a feature request. I'd like a toggle that would only allow stations to auto store in containers that already contain at least one of the item. If none are found, drop the output on the ground. 

That would really help organize the output and reduce the randomness. For example, right now I have a couple of smelters outputting to multiple chests nearby. I just want them all to go into a single chest. I realize I can reduce the radius for pickup and not have as many chests near, but many other "auto store" mods have this feature and it's very handy and something I've come to rely on.

### Steps to reproduce the bug

1. Have multiple machines producing items within range of multiple chests.
2. Items go into multiple chests rather than a single chest.

**Comment by eideehi** [comment] 2023-04-18 14:35
I will add this option to the TODO list.

Sorry, but since this issue is not a bug report, I will close it.

**Closed by eideehi** 2023-04-18 14:35 UTC
Labels: suggestion & request
