### ISSUE TITLE
Automatic Door is no longer per player

### ISSUE THREAD

**Issue by TriggerHappyBro** [eideehi/valheim-automatics#34] opened 2022-12-27 06:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Mod version

1.4.0

### Is this a bug caused by this mod alone?

This mod alone did not reproduce the bug

### List of mods to reproduce bug

Lots (24) but it was working fine before updating this mod to 1.4.0 (no other mods were updated). Discovered it earlier today and didn't get a chance to test it without other mods.

### What happened?

Expected: I(host) can have Automatic Door enabled while another player has it disabled and doors will only open automatically for me (or that the host's setting will override other players' whenever the host is present).
Actual: Whoever was first to enter an area (or has otherwise been there the longest) will override the other's setting.

Note: I was hosting locally (via the "Start Server" menu option) and have Automatic Door enabled, other player does not.

Side note: I *think* this might happen to other features (automatic processing) as well but haven't properly tested them.

### Steps to reproduce the bug

1. Have Automatic Door enabled
2. Enter an area no one else is in (e.g. via long distance portal)
3. Note functioning auto-doors
4. Have another player with Automatic Door disabled enter area
5. Note Automatic Doors apply for all
6. Have original auto-door player leave area and return
7. Note doors no longer open automatically.

**Comment by eideehi** [comment] 2023-03-11 07:50
The door not closing automatically is a bug. Fixed in commit 50313953d00ba1797f0475cf6f820aaa603e125c.

It is not a bug that automatic doors are enabled for players other than the host; it is a specification. Automatics are not designed to work only for the host. (Automatics was never designed to work on the server side in the first place...)

**Closed** 2023-03-11 12:01 UTC
Labels: bug, unintended behavior
